<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	  <NoWarn>NU1901;NU1902;NU1903;NU1904</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="DTOs\Agents\" />
    <Folder Include="DTOs\Properties\" />
    <Folder Include="Views\Properties\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCoreHero.ToastNotification" Version="1.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NextHouse.Application\NextHouse.Application.csproj" />
    <ProjectReference Include="..\NextHouse.Domain\NextHouse.Domain.csproj" />
    <ProjectReference Include="..\NextHouse.Persistence\NextHouse.Persistence.csproj" />
  </ItemGroup>

</Project>
